Repository wiremock/wiremock, pull requests merged in 2023-04, with the labels that each got.

#2124 Add community badges to the README
  README.md
Labels: documentation

#2129 Fix the Slack link in the contributing guide
  CONTRIBUTING.md
  README.md
Labels: bug, documentation

#2136 Add support filename template
  src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java
  src/main/java/com/github/tomakehurst/wiremock/common/SafeNames.java
  src/main/java/com/github/tomakehurst/wiremock/common/filemaker/FilenameMaker.java
  src/main/java/com/github/tomakehurst/wiremock/common/filemaker/FilenameTemplateModel.java
  src/main/java/com/github/tomakehurst/wiremock/core/Options.java
  src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java
  src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingBodyExtractor.java
  src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingGenerator.java
  src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java
  src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
  src/main/java/com/github/tomakehurst/wiremock/standalone/JsonFileMappingsSource.java
  src/test/java/com/github/tomakehurst/wiremock/MappingsLoaderAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/RecordingDslAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/SnapshotDslAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/WireMockServerTests.java
  src/test/java/com/github/tomakehurst/wiremock/common/FilenameMakerTest.java
  src/test/java/com/github/tomakehurst/wiremock/common/SafeNamesTest.java
  src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingBodyExtractorTest.java
  src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingGeneratorTest.java
  src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
  src/test/java/com/github/tomakehurst/wiremock/standalone/JsonFileMappingsSourceTest.java
Labels: enhancement

#2157 code changes for adding support for form parameter matching
  src/main/java/com/github/tomakehurst/wiremock/client/BasicMappingBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/client/MappingBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/client/ScenarioMappingBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/extension/requestfilter/RequestWrapper.java
  src/main/java/com/github/tomakehurst/wiremock/http/FormParameter.java
  src/main/java/com/github/tomakehurst/wiremock/http/Request.java
  src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java
  src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java
  src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java
  src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java
  src/main/java/com/github/tomakehurst/wiremock/verification/diff/EmptyToStringRequestWrapper.java
  src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/MockRequest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilderTest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternTest.java
  src/test/java/com/github/tomakehurst/wiremock/testsupport/MockRequestBuilder.java
  src/test/java/com/github/tomakehurst/wiremock/verification/diff/PlainTextDiffRendererTest.java
  src/test/resources/not-found-diff-sample_form.txt
Labels: enhancement
