Repository wiremock/wiremock, pull requests merged in 2023-07, with the labels that each got.

#2177 Remove duplicate dependencies
  build.gradle
Labels: chore

#2243 Add WireMock Java Co-Maintainers as codeowners
  .github/CODEOWNERS
Labels: chore

#2213 Add changelog generation with Release Drafter
  .github/release-drafter.yml
  .github/workflows/changelog-draft,yml
Labels: chore

#2245 add-exports in eclipse configuration
  build.gradle
Labels: chore

#2219 Fixed @WireMockTest not working with @DisabledInNativeImage
  src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java
Labels: bug

#2175 feat: add a requestedFor method allowing to pass Http method as parameter
  src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java
  src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java
Labels: enhancement, needs-tom

#2254 Remove dependencies on new:ing collections with Guava (refs #2111)
  src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/recording/RecordSpecBuilder.java
  src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilderTest.java
  src/test/java/com/github/tomakehurst/wiremock/testsupport/MockRequestBuilder.java
Labels: chore

#2253 Add mising schema properties
  src/main/resources/swagger/schemas/request-pattern.yaml
  src/main/resources/swagger/schemas/stub-mapping.yaml
Labels: bug

#2256 Replace Guava Files management with STL (refs #2111)
  src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java
  src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/standalone/JsonFileMappingsSourceTest.java
  src/test/java/com/github/tomakehurst/wiremock/store/files/BlobStoreFileSourceTest.java
Labels: chore

#2192 Add convenient method for matching absence of query param in a request
  src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java
  src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java
  src/test/java/ignored/Examples.java
Labels: enhancement

#2193 Add convenient method for matching absence of form param in a request
  src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java
  src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java
  src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java
Labels: enhancement

#2261 Added patch Method with URL in WireMock.java
  src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java
Labels: enhancement

#2255 ServerEvent: replace Guava predicate and function with STL (refs #2111)
  src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java
  src/main/java/com/github/tomakehurst/wiremock/stubbing/ServeEvent.java
Labels: chore, breaking, needs-tom

#2267 Improve error message in AbstractFileSource#assertFilePathIsUnderRoot()
  src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java
Labels: enhancement

#2272 Update Spotless to 6.17.0 and Google Java Format to 1.17.0
  build.gradle
Labels: dependencies

#2277 Fix ParseJsonHelper not storing parsed result in variable (if any) when json is empty
  src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelper.java
  src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMappingJsonRecorder.java
  src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
  src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelperTest.java
Labels: bug

#2139 ConsoleNotifyingWiremockNetworkTrafficListener accepts custom encoding
  src/main/java/com/github/tomakehurst/wiremock/http/trafficlistener/ConsoleNotifyingWiremockNetworkTrafficListener.java
  src/test/java/com/github/tomakehurst/wiremock/http/trafficlistener/ConsoleNotifyingWiremockNetworkTrafficListenerTest.java
Labels: enhancement

#2247 Fix flood json string can not be null or empty from mapping matcher
  src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPattern.java
  src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPatternTest.java
Labels: bug

#2274 Add IntelliJ Run Configurations
  .run/Build WireMock.run.xml
  .run/Publish to Maven local.run.xml
  .run/Run Spotless.run.xml
  .run/Run Tests.run.xml
  CONTRIBUTING.md
Labels: chore

#2283 Adds WiremockNetworkTrafficListeners
  src/main/java/com/github/tomakehurst/wiremock/http/trafficlistener/ConsoleNotifyingWiremockNetworkTrafficListener.java
  src/main/java/com/github/tomakehurst/wiremock/http/trafficlistener/NotifyingWiremockNetworkTrafficListener.java
  src/main/java/com/github/tomakehurst/wiremock/http/trafficlistener/WiremockNetworkTrafficListeners.java
  src/test/java/com/github/tomakehurst/wiremock/http/trafficlistener/ConsoleNotifyingWiremockNetworkTrafficListenerTest.java
  src/test/java/com/github/tomakehurst/wiremock/http/trafficlistener/NotifyingWiremockNetworkTrafficListenerTest.java
Labels: enhancement, extensibility, needs-tom
