Repository wiremock/wiremock, pull requests merged in 2023-10, with the labels that each got.

#2409 Replace Guava by JDK (Partly)
  src/test/java/com/github/tomakehurst/wiremock/extension/mappingssource/MappingsLoaderExtensionTest.java
Labels: chore

#2424 feat: remove unnecessary unboxing
  src/main/java/com/github/tomakehurst/wiremock/http/multipart/FileUpload.java
  src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
  src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java
Labels: chore

#2443 doc: turn reference link into actual link
  src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java
Labels: documentation

#2435 Update the co-maintainer policy beyond WireMock 3
  CONTRIBUTING.md
Labels: documentation, needs-tom

#2423 Do not use deprecated jackson iso8601 class
  src/main/java/com/github/tomakehurst/wiremock/admin/Conversions.java
  src/main/java/com/github/tomakehurst/wiremock/common/Dates.java
  src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
  src/test/java/com/github/tomakehurst/wiremock/admin/ConversionsTest.java
  src/test/java/com/github/tomakehurst/wiremock/common/DateTimeOffsetTest.java
  src/test/java/com/github/tomakehurst/wiremock/common/DatesTest.java
  src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsCurrentDateHelperTest.java
  src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseDateHelperTest.java
Labels: chore

#2450 Replace Optional.orElse() calls with Optional.orElseGet()
  src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java
  src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java
  src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java
  src/main/java/com/github/tomakehurst/wiremock/common/ClasspathFileSource.java
  src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java
  src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPattern.java
  src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java
Labels: chore, hacktoberfest-acepted

#2467 Add null check for actual date/time truncation (#2466)
  src/main/java/com/github/tomakehurst/wiremock/common/DateTimeTruncation.java
Labels: bug
