Repository wiremock/wiremock, pull requests merged in 2023-08, with the labels that each got.

#2140 Correctly handle scenarios with transformed stubs
  src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingPostProcessor.java
  src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingPostProcessorTest.java
Labels: bug, breaking, needs-tom

#2300 Update the release drafter config for beta versioning
  .github/release-drafter.yml
Labels: chore

#2302 Bump jetty-bom from 11.0.12 to 11.0.15
  build.gradle
Labels: dependencies

#2314 Fix HttpsBrowserProxyAcceptanceTest
  src/test/java/com/github/tomakehurst/wiremock/HttpsBrowserProxyAcceptanceTest.java
Labels: chore

#2299 Change Queue on to Deque in InMemoryRequestJournalStore
  src/main/java/com/github/tomakehurst/wiremock/recording/Recorder.java
  src/main/java/com/github/tomakehurst/wiremock/store/InMemoryRequestJournalStore.java
  src/main/java/com/github/tomakehurst/wiremock/verification/AbstractRequestJournal.java
  src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/RecordApiAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/ServeEventLogAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/SnapshotDslAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/recording/ProxiedServeEventFiltersTest.java
  src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingGeneratorTest.java
Labels: enhancement, needs-tom

#2305 Replace Guava by JDK (Partly)
  src/main/java/com/github/tomakehurst/wiremock/common/ContentTypes.java
  src/main/java/com/github/tomakehurst/wiremock/common/ParameterUtils.java
  src/main/java/com/github/tomakehurst/wiremock/common/xml/XmlNode.java
  src/main/java/com/github/tomakehurst/wiremock/extension/ExtensionLoader.java
  src/main/java/com/github/tomakehurst/wiremock/extension/Extensions.java
  src/main/java/com/github/tomakehurst/wiremock/extension/requestfilter/RequestWrapper.java
  src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java
  src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/SystemKeyAuthoriser.java
  src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/PickRandomHelper.java
  src/main/java/com/github/tomakehurst/wiremock/http/HttpHeader.java
  src/main/java/com/github/tomakehurst/wiremock/http/HttpHeaders.java
  src/main/java/com/github/tomakehurst/wiremock/http/LoggedResponse.java
  src/main/java/com/github/tomakehurst/wiremock/http/multipart/FileItemPartAdapter.java
  src/main/java/com/github/tomakehurst/wiremock/matching/ContentPatternDeserialiser.java
  src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java
  src/main/java/com/github/tomakehurst/wiremock/matching/MatchesXPathPattern.java
  src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java
  src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java
  src/main/java/com/github/tomakehurst/wiremock/recording/LoggedResponseDefinitionTransformer.java
  src/main/java/com/github/tomakehurst/wiremock/recording/Recorder.java
  src/main/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessor.java
  src/main/java/com/github/tomakehurst/wiremock/security/ClientTokenAuthenticator.java
  src/main/java/com/github/tomakehurst/wiremock/security/TokenAuthenticator.java
  src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java
  src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
  src/main/java/com/github/tomakehurst/wiremock/stubbing/AbstractScenarios.java
  src/main/java/com/github/tomakehurst/wiremock/stubbing/AbstractStubMappings.java
  src/main/java/com/github/tomakehurst/wiremock/stubbing/Scenario.java
  src/main/java/com/github/tomakehurst/wiremock/stubbing/SortedConcurrentMappingSet.java
  src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java
  src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonPathHelperTest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/StringValuePatternTest.java
  src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingPostProcessorTest.java
  src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMatchers.java
  wiremock-webhooks-extension/src/test/java/testsupport/WireMockResponse.java
Labels: chore

#2343 Revert Release Drafter to semver after the 3.0.0 release
  .github/release-drafter.yml
Labels: chore

#2344 Ensure that the shadow JAR is always built last
  build.gradle
  wiremock-webhooks-extension/build.gradle
Labels: bug

#2339 Stop returning 500s for unmatched path patterns
  src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java
  src/test/java/com/github/tomakehurst/wiremock/verification/diff/DiffTest.java
  src/test/java/com/github/tomakehurst/wiremock/verification/diff/PlainTextDiffRendererTest.java
  src/test/resources/not-found-diff-sample_json-path-body-not-json.txt
  src/test/resources/not-found-diff-sample_json-path-no-body.txt
Labels: bug
