Repository wiremock/wiremock, pull requests merged in 2023-11, with the labels that each got.

#2451 Fix contract for FileSourceBlobStore
  src/main/java/com/github/tomakehurst/wiremock/store/files/FileSourceBlobStore.java
  src/test/java/com/github/tomakehurst/wiremock/store/files/FileSourceBlobStoreTest.java
Labels: bug, hacktoberfest-accepted

#2463 fix: introduce a slight delay given the 2-3 results is slightly flakey
  src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
Labels: chore, hacktoberfest-accepted

#2468 chore: use List.of where possible if only one argument is passed
  src/main/java/com/github/tomakehurst/wiremock/common/UniqueFilenameGenerator.java
  src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonData.java
  src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelper.java
  src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilderTest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilderTest.java
Labels: chore, hacktoberfest-accepted

#2460 Refactor: split getLines method of Diff class
  src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java
Labels: bug, hacktoberfest-accepted

#2449 Fixed #2415 Gradle replaces SLF4J-API 1.7.36 with 2.0.7, causing warning in the log
  src/main/resources/META-INF/services/wiremock.org.slf4j.spi.SLF4JServiceProvider
Labels: bug, needs-tom, hacktoberfest-accepted

#2421 Proposal for: Flaky port allocation tests #2281
  src/main/java/com/github/tomakehurst/wiremock/jetty/JettyHttpServer.java
  src/test/java/com/github/tomakehurst/wiremock/jetty11/JettyHttpServerTest.java
Labels: chore, hacktoberfest-accepted

#2490 Fix `NullPointerException` in `ResponseDefinition.getProxyUrl()`
  src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java
  src/test/java/com/github/tomakehurst/wiremock/http/ResponseDefinitionTest.java
Labels: bug
