Repository wiremock/wiremock, pull requests merged in 2023-09, with the labels that each got.

#2351 fix: avoid crash when printing help in wiremock-standalone
  build.gradle
  src/main/resources/wiremock/joptsimple/HelpFormatterMessages.properties
Labels: bug

#2358 Add working equals & readable toString to NetworkAddressRange
  src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRange.java
Labels: enhancement

#2366 Fix standalone missing filename extension bug
  src/main/java/com/github/tomakehurst/wiremock/common/filemaker/FilenameMaker.java
  src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
  src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java
Labels: bug

#1738 Fix admin requests with empty body to avoid response code 411
  src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java
  src/test/java/com/github/tomakehurst/wiremock/client/HttpAdminClientTest.java
Labels: bug, needs-tom

#2375 Fix MD links
  README.md
Labels: chore

#2377 Fixed #2364 - scenarios produced by recorder play back in reverse order
  src/main/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessor.java
  src/test/java/com/github/tomakehurst/wiremock/RecordApiAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/RecordingDslAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/SnapshotDslAcceptanceTest.java
  src/test/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessorTest.java
Labels: bug

#2381 Print loaded extensions at startup
  src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java
  src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java
  src/main/java/com/github/tomakehurst/wiremock/extension/Extensions.java
  src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java
Labels: enhancement

#2389 Include more info when webhook refusal logged
  src/main/java/org/wiremock/webhooks/Webhooks.java
  src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaPostServeActionTest.java
  src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaServeEventTest.java
Labels: enhancement

#2390 Fix json string schema rejecting numbers
  src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPattern.java
  src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPatternTest.java
  src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternTest.java
Labels: bug

#2334 Exposing MappingsSource for extension point
  src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java
  src/main/java/com/github/tomakehurst/wiremock/extension/MappingsLoaderExtension.java
  src/test/java/com/github/tomakehurst/wiremock/extension/mappingssource/DummyMappingsLoaderExtension.java
  src/test/java/com/github/tomakehurst/wiremock/extension/mappingssource/MappingsLoaderExtensionTest.java
  src/test/resources/extension-test-request/200-example.json
Labels: enhancement, extensibility, needs-tom
